### ISSUE TITLE
On phone, the About link gets cut off

### ISSUE THREAD

**Issue by michellemas** [BI/octo-wookie#170]
Samsung S5:

On Home page; cannot see that "about" is a link because the underline is cut off.

![screenshot_2015-06-30-16-45-08](https://cloud.githubusercontent.com/assets/3418009/8441776/757e9f46-1f48-11e5-9526-e3d27a2a8b60.png)

**Comment by michellemas** [comment]
About and Contact link looks good!

**Comment by owen-dall** [comment]
Same on the iPhone....
