### ISSUE TITLE
Add Text to our Adverse Events Visualization Card

### ISSUE THREAD

**Issue by owen-dall** [BI/octo-wookie#179]
"The following information is from the FDA Adverse Event Reporting System (FAERS): 2004-2014"

For more information go to the FDA site:
http://www.fda.gov/Drugs/GuidanceComplianceRegulatoryInformation/Surveillance/AdverseDrugEffects/

**Comment by michellemas** [comment]
The Adverse Events tab is now a scrolling page and the bottom border from charts is gone. Any chance that we could reduce line spacing or move the line "For more information go to the FDA site."  to be in same line as first sentence?

**Comment by jackcompton** [comment]
Border is there, it might just be below the scroll on your resolution.

**Comment by owen-dall** [comment]
Yes, I don't see that issue either.  Resolved.




*-Owen*


*Owen Dall*

*Vice President | Chief Technology Officer*

*Barquin International*

*Office: 202.296.7147 | Mobile: 410.991.0811*

*Fax: 202.296.8903 | email:** odall@barquin.com <odall@barquin.com>*

[image: BI_Logo_2012_JPEG]



NOTICE: If you have received this message in error, please contact the
sender immediately and be aware that the use, copying, or dissemination of
this information is prohibited. This email transmission contains
information from Barquin International that may be considered privileged or
confidential and is intended solely for the named recipient.

**Comment by michellemas** [comment]
It does not scroll on Owen/Jack's computer. After discussion it was decided that this is a pass.
