### ISSUE TITLE
Update 'About' page with revised text

### ISSUE THREAD

**Issue by michellemas** [BI/octo-wookie#211]
@iyameen will provide the revised text.

**Comment by michellemas** [comment]
@iyameen @owen-dall 
Change requested by Owen in the second paragraph to reference openFDA - the line "openFDA Application Programming Interface (API)" should be a link that takes you to the openFDA website:

Development of the site tests an organization’s ability to apply agile development techniques over a short period of time using open source technology on open data provided exclusively for this RFQ. The source of the data is the Food and Drug Administration (FDA) collections related to enforcements, adverse events and labeling of drugs, food and medical devices provided via openFDA Application Programming Interface (API). Developers were asked to design and deploy an application that serves a purpose and is useful to specific communities of interested people (e.g., patients, researchers, manufacturers).

**Comment by YeahButHats** [comment]
@owen-dall 

That text isn't in the second paragraph. Do you want the text changed or just the link?

**Comment by owen-dall** [comment]
"The source of the data is the Food and Drug Administration (FDA) collections related to enforcements, adverse events and labeling of drugs, food and medical devices as provided by the openFDA Application Programming Interface (API)."

Please make "openFDA" the highlighted link to https://open.fda.gov/

**Comment by michellemas** [comment]
@YeahButHats : Need to change text to add the part about "as provided by the openFDA Application Programming Interface (API)." and make openFDA a link. Hope that clarifies? Would you like to talk?

**Comment by michellemas** [comment]
Also, www.barquin.com should be a link.

**Comment by jackcompton** [comment]
I had a thought - a little late for this project, but something good to consider for the future:

We should try using markdown for all content - i.e. the content author writes it in markdown, and the developer uses markdown parser(s) for all content presentation.

This allows straight forward copy pasting to preserve the author's intent. 

A permanent solution to a recurring problem.

**Comment by owen-dall** [comment]
Agreed this for the future.

**Comment by michellemas** [comment]
2 issues for www.barquin.com and the openFDA link will be part of a future release. This ticket will be  closed.
